INSERT INTO pacientes_enfermedades(`id`, `nombre_enfermedad`) VALUES
(1, 'Alergias'),
(2, 'Catarro'),
(3, 'Conjuntivitis'),
(4, 'Desmayo'),
(5, 'Dolor de cabeza'),
(6, 'Infección de garganta'),
(7, 'Infección de Oído'),
(8, 'Lesión en la piel'),
(9, 'Meningitis'),